### ISSUE TITLE
move the fhir model classes to their own project

### ISSUE THREAD

**Issue by fernandezpablo85** [intervention-engine/fhir#10]
It's useful for implementors to use the fhir classes without depending on mongodb, have you considered moving those to their own (dependency-less) github project?

**Comment by cmoesel** [comment]
We haven't really considered this in the past, but it's something we certainly *could* consider.  We would want the models to still have the bson tags, since that's important for our mgo implementation, but it wouldn't require an actual dependency on mgo-- so I expect that would be fine for your purposes.

I'll talk with the rest of the team and see what they think.

**Comment by ahubley** [comment]
@fernandezpablo85 we discussed this issue this morning, and looking at the `fhir/models` package, we found that the only dependencies on mgo were in legacy code that we needed to remove anyway. Now that those dependencies have been removed, you should be able to `import "github.com/intervention-engine/fhir/models"` and use the fhir structs on their own.

**Comment by fernandezpablo85** [comment]
Thanks @ahubley

**Comment by ahubley** [comment]
No problem! I'll close this issue.
