### ISSUE TITLE
Invalid Observation search parameter returning results

### ISSUE THREAD

**Issue by cjduffett** [intervention-engine/fhir#128]
The following query does not cause an error, and returns a set of 100 random Observation results:
https://syntheticmass.mitre.org/fhir/Observation?code:50050

This should cause an error, no?

**Comment by cmoesel** [comment]
I'm not sure.  Technically, I think it's an unknown parameter (_code:50050_) -- and leaders of the FHIR community have made it pretty clear that they think unknown parameters should be _ignored_.  I suspect that's what we're doing -- and the 100 "random" observations are the same (or at least similar) to what you would receive if you had no search parameter at all.

**Comment by cmoesel** [comment]
BTW-- I fought the fight against that idea, arguing that unknown parameters should return an error, but I lost that battle.

**Comment by cjduffett** [comment]
☹️  Okay so this is not technically an issue then?

**Comment by cmoesel** [comment]
I don't think so...  But I suppose if we want to try to detect user errors like this (using `:` instead of `=`) we could do so.  But at the end of the day, I think the FHIR stance is that this type of mistake should never make it to a production client anyway and it is difficult to discern mistakes from intentional extra parameters (although I have no idea why someone would intentionally send extra parameters).
