### ISSUE TITLE
Conformance Statement?

### ISSUE THREAD

**Issue by ghchinoy** [intervention-engine/fhir#23]
Any thoughts on how to include/generate a [conformance statement](http://hl7.org/fhir/conformance.html) for this server?  (from [implementer's check list](http://hl7.org/fhir/implementation.html))

Ideas could be - create a conformance model (Resource) and manually populate it, or find a way to introspect the go code to determine which models and parameters are implemented and then generate the conformance model?

**Comment by cmoesel** [comment]
To be honest, we haven't really considered publishing conformance at this point.  We developed this server mainly as the backend FHIR server for our Intervention Engine web application -- and that is what drives the priorities of what we support and don't support.

That said, we've purposely worked to keep this code-base clean of Intervention-Engine-specific features so that it _could_ be used as a more general purpose FHIR server as well.  To that end, if we want to encourage use by others, it _does_ make sense to support the conformance statements.  We'll have to prioritize this against other needs to determine when it can be done.  Of course, we'd also be glad to accept a well-written Pull Request that implements it.

In regards to approach, I expect it would be some hybrid of generated conformance statements and manually written conformance statements.  Much of this server (specifically resource definitions and search parameter definitions) is generated from a fork of the FHIR tool chain (the latest of which is [here](https://github.com/intervention-engine/fhir-golang-generator/tree/dstu2_refresh)).  I expect we would update the generator to spit out code that describes some of the conformance for us -- and then add the rest via some manually written extension.

In brief, what do we support now?  We support all of the CRUD operations on all of the DSTU2 resources -- but in JSON format only (we do _not_ support XML).  We support most resource-specific search parameters (including chained searches), with the exception of _composite_ search parameters.  We don't support most of the search parameters defined for all resources (e.g., the ones starting with \_), but we do support \_id and \_count.  We're starting to support posting bundles as transactions (but right now, only support creating new resources in them and we don't execute as atomic transactions)...  And anything else I haven't mentioned here -- we probably don't support it.

Thanks for asking!

**Comment by cjduffett** [comment]
A conformance statement has now been added in the stu3_mar2016 branch.
