### ISSUE TITLE
date comparison operator for _lastUpdated is not supported in search query

### ISSUE THREAD

**Issue by mlos100** [intervention-engine/fhir#46]
Invoking something like the following results in a Operation Outcome with Error 500

http://localhost:8881/Bundle?_lastUpdated=%3E%3D2016-02-09T13%3A57%3A01.686-05%3A00

The above is seeking resources that have been updated since a specified time.  The need is to allow message recipients to query for "new" messages addressed to them.

**Comment by cmoesel** [comment]
There were two issues here:

1. The decoded URL is "http://localhost:8881/Bundle?_lastUpdated=>=2016-02-09T13:57:01.686-05:00".  The ">=" operator is not a valid comparison operator.  Instead, "ge" should be used, per section [2.1.1.4.5](http://hl7.org/fhir/DSTU2/search.html#prefix).

2. There was a typo in our code that resulted in `_lastUpdated` not being processed correctly.  This was fixed in pull request #47.
