### ISSUE TITLE
Searching for message:MessageHeader.destination-uri now returns OperationOutcome and no result

### ISSUE THREAD

**Issue by mlos100** [intervention-engine/fhir#93]
Querying FHIR server for /Bundle?message:MessageHeader.destination-uri=urihere is no longer returning search results.  Instead, an operation outcome with an error is returned.

Querying for /Bundle?message:MessageHeader works as expected.

A patch file with a suggested unit test is attached. 

This uri against the IE FHIR Server embedded with ptmatch returns the json below:
http://localhost:3001/Bundle?message:MessageHeader.destination-uri=http://mitre.org/ptmatchadapter-fril

{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "details": {
                "coding": [
                    {
                        "system": "http://hl7.org/fhir/ValueSet/operation-outcome",
                        "code": "MSG_PARAM_MODIFIER_INVALID",
                        "display": "Parameter \"message\" modifier is invalid"
                    }
                ],
                "text": "Parameter \"message\" modifier is invalid"
            }
        }
    ]

}

**Comment by cmoesel** [comment]
It looks like we're not properly handling the case where there is a modifier _and_ a chained parameter.  I believe I've found the source of the problem here:

https://github.com/intervention-engine/fhir/blob/master/search/search_param_types.go#L997

In short, that second `if` statement and `split` function should operate against `param` -- not `fullParam`.

In your bug report, you referenced an attached unit test, but I do not see one.  If you submit it, I can integrate it and try making the fix described above.  Or please feel free to fix the issue on a branch off master and submit a PR.

**Comment by mlos100** [comment]
Attached patch file.

Don’t know what happened to attachment on issue. Originally tried creating a branch but didn’t have permissions and was too lazy to fork, etc.

**Comment by mlos100** [comment]
Reattaching patch file with a supported txt  extension.

[search_dest_uri.patch.txt](https://github.com/intervention-engine/fhir/files/493102/search_dest_uri.patch.txt)

**Comment by cmoesel** [comment]
I have a fix in hand.  I am just waiting for an existing PR to be merged first, then I will issue a new PR with the fix.
